# Generated by Django 4.0.2 on 2022-02-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('year', models.IntegerField(verbose_name=4)),
                ('description', models.CharField(max_length=500)),
                ('precio', models.IntegerField(verbose_name=4)),
                ('desarrolladora', models.ManyToManyField(to='api.Desarrolladora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.genero')),
            ],
        ),
    ]
